import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useEffect, useRef, useState } from 'react';
import { css } from '@emotion/react';
import Button from '../components/Button';

export default function Home() {
  const inputRef = useRef(null);
  const [products, setProducts] = useState([]);

  // useEffect(() => {
  //   fetch('/api/get-items')
  //     .then((res) => res.json())
  //     .then((data) => setProducts(data.items));
  // }, []);
  useEffect(() => {
    fetch('/api/get-products')
      .then((res) => res.json())
      .then((data) => setProducts(data.items));
  }, []);

  const handleClick = () => {
    if (inputRef.current == null || inputRef.current.value === '') {
      alert('이름을 입력해 주세요');
      return;
    }
    fetch(`/api/add-item?name=${inputRef.current.value}`)
      .then((res) => res.json())
      .then((data) => alert(data.message));
  };

  const getDetailInfo = (item, value) => {
    fetch(`/api/get-detail?pageId=${item.id}&propertyId=${value.id}`)
      .then((res) => res.json())
      .then((data) => alert(JSON.stringify(data)));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <input
          ref={inputRef}
          className="placeholder:italic placeholder:text-slate-400 block bg-white w-96 border border-slate-300 rounded-md py-2 pl-3 pr-3 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 sm:text-sm"
          type="text"
          placeholder="name"
        />
        <button
          css={css`
            background-color: hotpink;
            padding: 16px;
            border-radius: 8px;
          `}
          onClick={handleClick}
        >
          {' '}
          Add Jacket
        </button>
        <Button onClick={handleClick}>Add Jacket2 </Button>

        <div>
          <p>Product List</p>
          {products &&
            products.map((item) => (
              <div key={item.id}>
                {item.name} <p>{item.createdAt}</p>
              </div>
            ))}

          {/*Notion API 버전*/}
          {/*{products &&*/}
          {/*  products.map((item) => (*/}
          {/*    <div key={item.id}>*/}
          {/*      {JSON.stringify(item)}*/}
          {/*      {item.properties &&*/}
          {/*        Object.entries(item.properties).map(([key, value]) => (*/}
          {/*          <button*/}
          {/*            key={key}*/}
          {/*            onClick={() => {*/}
          {/*              getDetailInfo(item, value);*/}
          {/*            }}*/}
          {/*          >*/}
          {/*            {key}*/}
          {/*          </button>*/}
          {/*        ))}*/}
          {/*      <br />*/}
          {/*      <br />*/}
          {/*    </div>*/}
          {/*  ))}*/}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
